// <auto-generated />
using System;
using ExampleRegistry.Projections.Api;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExampleRegistry.Projections.Api.Migrations
{
    [DbContext(typeof(ApiProjectionsContext))]
    partial class ApiProjectionsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Be.Vlaanderen.Basisregisters.ProjectionHandling.Runner.ProjectionStates.ProjectionStateItem", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Position");

                    b.HasKey("Name")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ProjectionStates","Api");
                });

            modelBuilder.Entity("ExampleRegistry.Projections.Api.ExampleAggregateDetail.ExampleAggregateDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NameDutch")
                        .HasMaxLength(200);

                    b.Property<string>("NameEnglish")
                        .HasMaxLength(200);

                    b.Property<string>("NameFrench")
                        .HasMaxLength(200);

                    b.Property<string>("NameGerman")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("NameDutch")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ExampleAggregateDetails","Api");
                });

            modelBuilder.Entity("ExampleRegistry.Projections.Api.ExampleAggregateList.ExampleAggregateList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("Name")
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("ExampleAggregateList","Api");
                });
#pragma warning restore 612, 618
        }
    }
}
